version: '3.8'

services:
  devercotmagic:
    container_name: my_julia_container  # Custom container name
    build: .
    volumes:
      - .:/home/juliauser/ErcotMagic
    ports:
      - "8080:8080"
    environment:
      - PATH="/venv/bin:$PATH:/usr/local/julia/bin:/usr/local/bin"
    command: tail -f /dev/null
  
  bqload: 
    container_name: my_bqload_container  # Custom container name
    build: .
    volumes:
      - .:/home/juliauser/ErcotMagic
    ports:
      - "8080:8080"
    environment:
      - PATH="/venv/bin:$PATH:/usr/local/julia/bin:/usr/local/bin"
    command: tail -f /dev/null