version: '3.8'

services:
  devercotmagic:
    container_name: my_julia_container  # Custom container name
    build: .
    volumes:
      - .:/home/juliauser/ErcotMagic
      - /home/swojcik/.ercotmagic/nanocentury-credentials.json:/home/juliauser/.gcloud/key.json
      - /home/swojcik/.julia/config/startup.jl:/home/juliauser/.julia/config/startup.jl
    #ports:
      #- "8080:8080"
    environment:
      - PATH="/venv/bin:$PATH:/usr/local/julia/bin:/usr/local/bin"
      - GOOGLE_APPLICATION_CREDENTIALS="/home/juliauser/.gcloud/key.json"
    command: tail -f /dev/null
  
  bqload: 
    container_name: my_bqload_container  # Custom container name
    build: .
    volumes:
      - .:/home/juliauser/ErcotMagic
      - /home/swojcik/.ercotmagic/nanocentury-credentials.json:/home/juliauser/.gcloud/key.json
      - /home/swojcik/.julia/config/startup.jl:/home/juliauser/.julia/config/startup.jl
    #ports:
      #- "8080:8080"
    environment:
      - PATH="/venv/bin:$PATH:/usr/local/julia/bin:/usr/local/bin"
      - GOOGLE_APPLICATION_CREDENTIALS="/home/juliauser/.gcloud/key.json"
    command: tail -f /dev/null